[project]
name = "sim-data-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.9.2",
    "networkx>=3.4.2",
    "polars>=1.12.0",
    "pyyaml>=6.0.2",
]
